### ISSUE TITLE
Invalid trailing whitespace in version URI

### ISSUE THREAD

**Issue by lawley** [IHTSDO/termserver-syndication#3]
https://github.com/IHTSDO/termserver-syndication/blob/3ac543a9daa30b17d26f9b0ee01d871e02b6e7f8/feed-example.xml#L45

**Comment by rorydavidson** [comment]
Fixed in commit - https://github.com/IHTSDO/termserver-syndication/commit/4c22bc4f75939277072c6bf55912648aa4fbc989
